services:
  frontend:
    container_name: frontend
    ports:
      - "5173:5173"
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    container_name: backend
    ports:
      - "3000:3000"
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
  mongodb:
    image: mongo:latest
    command: mongod --quiet
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local
